accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
  
]

crypto/urls.py
from django.conf.urls import url
from . import views

app_name='crypto'

urlpatterns = [
    
    url(r'^sell/$',views.sell_block,name="sell"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),
    #url(r'^error/$',views.error,name="error"),
]

digifest2k18/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
app_name="main"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home,name="home"),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^crypto/',include('crypto.urls')),
    
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

# class users(models.Model):
#     bhamashahid = models.CharField(max_length = 20)
#     balance = models.FloatField()
#     publicKey = models.CharField(max_length = 50)
#     pHash = models.CharField(max_length = 50)
#     joinTime = models.DateTimeField(auto_now_add=True)

crypto/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class blockDB(models.Model):
    data            = models.TextField(default = "")
    time            = models.DateTimeField(auto_now_add=True)
    previousHash    = models.CharField(max_length = 40)
    hashe           = models.CharField(max_length = 40)
    senderKey       = models.CharField(max_length = 50)
    receiverKey     = models.CharField(max_length = 50)
    amount          = models.FloatField(default = 0.0)
    

class testblockDB(models.Model):
    data            = models.TextField(default = "")
    time            = models.DateTimeField(auto_now_add=True)
    previousHash    = models.CharField(max_length = 40)
    hashe           = models.CharField(max_length = 40)
    senderKey       = models.CharField(max_length = 50)
    receiverKey     = models.CharField(max_length = 50)
    amount          = models.FloatField(default = 0.0)

class userFile(models.Model):
    lastMod          = models.DateTimeField(auto_now_add=True)
    userid           = models.CharField(max_length = 50)
    balance          = models.FloatField(default = 0.0)
    

crypto/forms.py
from django import forms
from . import blockchain
from . import models

class SellBlock(forms.ModelForm):
    class Meta:
        model = models.testblockDB
        fields = ['data','amount','senderKey','receiverKey']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.http import HttpResponse
from .scrap import returnFirstLastName
from crypto.blockchain import registrationReward

def signup_view(request):
    
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            instance = form.save(commit=False)
            
            firstName, lastName = returnFirstLastName(str(request.user))             # authentication Bhamashah Id
            
            instance.first_name = firstName
            instance.last_name = lastName
            instance.save()                 # saving instance
            
            # adding registration Reward
            temp = request.user
            print(temp)
            registrationReward(temp)
            
            return redirect('accounts:signup')
            
            
    else:
        form = UserCreationForm
    
    
    return render(request,'accounts/signup.html',{'form':form})



def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            return redirect('accounts:login')
    else:
        form = AuthenticationForm
    return render(request,'accounts/login.html',{'form':form})
    
    
def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('accounts:login')

crypto/views.py
from django.shortcuts import render
from .blockchain import newNode
from . import forms
import time
from django.http import HttpResponse
from django.contrib.auth.models import User   #user info

from .models import userFile

from hashlib import md5

# Create your views here.
# @login_required(login_url="/accounts/login/")
def dashboard(request):
    curr_user = request.user
    transactions = blockDB.objects.all() 
    
    
    return render(request,'dashboard.html',{'curr_user':curr_user})
    


def error(errorName):
    return HttpResponse(errorName)
    #return render(null,'crypto/error.html',{'error':errorName})
    

# -------------------------------------------------------------updating Data Function----------------------------------------------
def updateBalance(userid_, amount):
    usermd5 = md5(str(userid_).encode()).hexdigest()
    print("usermd5 = ",usermd5)
    # person = userFile.objects.all().filter(userid=usermd5)                 # return object with userid md5(userid.encode().hexstring
    userfile = userFile.objects.get(userid=usermd5)
    userfile.amount += amount
    userFile.objects.filter(userid=usermd5).update(lastMod = time.ctime())
	
    #Survey.objects.filter(pk=survey.pk).update(active=True)
	# updating new user's record
# 	person.save()


# ----------------------------------------------------------updating Data Function ends--------------------------------------------



def sell_block(request):
    
    if request.method=='POST':
        
        # getting last row data from transactions table
        
        form=forms.SellBlock(request.POST)
        
        if form.is_valid():
            
            instance = form.save()
            
            # storing form data in a list
            mlist = [str(instance.data), str(instance.amount), str(instance.senderKey), str(instance.receiverKey)]
            
            # print("mlist = ", mlist)
            
            ret = list(newNode(mlist))  # ret[0] = true /false  ret[1] = error string
            print(ret)
            if (ret[0]):
                updateBalance(request.user, float(instance.amount))
                return HttpResponse('DB saved')
            else:
                # errorFunc(error parameter)
                # handle error case with errorFunc
                error(ret[1])
            
            
            

    else:
        form = forms.SellBlock()
    return render(request,'crypto/sell_block.html',{'form':form})
    
    
    

# --------------------------------------------users data---------------------------------------------------------------

digifest2k18/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 style="margin:25px;">LOGIN</h1>
    <div class="container-fluid acc">
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}
   {{form}}
   <input type="submit" value="Login">
</form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 style="margin:25px;">SIGNUP</h1>
    <div class="container-fluid acc">
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {% csrf_token %}
   {{form}}
   <input type="submit" value="Signup">
</form>
</div>
{% endblock %}

crypto/templates/crypto/dashboard.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 style="margin:25px;">Dashboard</h1>
    <div class="container-fluid ">
     <span>Name Of User{{curr_user}}</span>
    <div class="personal-info">
    </div>
    <div class="buttons">
   <a href="{% url 'crypto:sell' %}" class="btn btn-info" role="button">Sell Rajcoins</a> 
    </div>
    <!--required transaction table -->
            
        
        
    </div>
{% endblock %}

crypto/templates/crypto/error.html
<!DOCTYPE html>
<html>
    <head>
        <title>Error</title>
    </head>>
    
    <body>
        {{error}}
    </body>
</html>

crypto/templates/crypto/sell_block.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 style="margin:25px;">SELL-COINS</h1>
    <div class="container-fluid acc">
<form class="site-form" action="{% url 'crypto:sell' %}" method="post">
  {% csrf_token %}
   {{form}}
   <input type="submit" value="Sell">
</form>
</div>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="img/fav.png">
		<!-- Author Meta -->
		<meta name="author" content="codepixer">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Rajcoin</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/style.css ' %}">
			<link rel="stylesheet" href="{% static 'css/linearicons.css ' %}">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">					
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
		</head>
  <body>
    <header id="header" id="home">
			    <div class="container">
			    	<div class="row align-items-center justify-content-between d-flex">
				      <div id="logo">
				         <a class="navbar-brand" href="#">RajCoin</a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li class="menu-active"><a href="#home">Home</a></li>
				         
				          <li><a href="#feature">Feature</a></li>
				          <li><a href="#price">Price</a></li>
				{% if user.is_authenticated %}
           
            <li class="nav-item">
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token%}
                <button class="logout" type="submit">Logout</button>
              </form>
            </li>

            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
            <li class="menu-has-children"><a href="">Pages</a>
				            <ul>
				              <li><a href="generic.html">About</a></li>
				              <li><a href="elements.html">Elements</a></li>
				            </ul>
				          </li>
				        </ul>
				      </nav><!-- #nav-menu-container -->		    		
			    	</div>
			    </div>
			  </header>
			  	<!-- start banner Area -->
			<section class="banner-area relative" id="home">
				<div class="overlay overlay-bg"></div>		
				<div class="container">
					<div class="row fullscreen d-flex align-items-center justify-content-start">
						<div class="banner-content col-lg-12 col-md-12">
							<h5 class="text-white text-uppercase">Currently Purchase Rate</h5>
							<h1 class="text-uppercase">
								₹0.00					
							</h1>
							<p class="text-white pt-20 pb-20">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp <br> or incididunt ut labore et dolore magna aliqua. Ut enim ad minim.
							</p>
							<a href="#" class="primary-btn header-btn text-uppercase">Buy Rajcoin</a>
						</div>												
					</div>
				</div>
			</section>
			<!-- End banner Area -->	

    {% block content %}
    {% endblock %}
  	<!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h4 class="text-white">About Us</h4>
								<p>
									Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.
								</p>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h4 class="text-white">Top Products</h4>
								<ul class="footer-menu">
									<li><a href="#">Managed Website</a></li>
									<li><a href="#">Managed Reputation</a></li>
									<li><a href="#">Managed Tools</a></li>
									<li><a href="#">Managed Service</a></li>
								</ul>
									
							</div>
						</div>						
						<div class="col-lg-6  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h4 class="text-white">Newsletter</h4>
								<p>You can trust us. we only send  offers, not a single spam.</p>
								<div class="d-flex flex-row" id="mc_embed_signup">
									  <form class="navbar-form" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get">
									    <div class="input-group add-on">
									      	<input class="form-control" name="EMAIL" placeholder="Email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email address'" required="" type="email">
											<div style="position: absolute; left: -5000px;">
												<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
											</div>
									      <div class="input-group-btn">
									        <button class="genric-btn"><span class="lnr lnr-arrow-right"></span></button>
									      </div>
									    </div>
									      <div class="info mt-20"></div>									    
									  </form>
								</div>
							</div>
						</div>						
					</div>
					<div class="footer-bottom d-flex justify-content-between align-items-center flex-wrap">
						<p class="footer-text m-0">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved 
						</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>	
			<!-- End footer Area -->

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
			<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
  			<script src="{% static 'js/easing.min.js' %}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>	
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>			
			<script src="{% static 'js/jquery.sticky.js' %}"></script>
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>			
			<script src="{% static 'js/parallax.min.js' %}"></script>	
			<script src="{% static 'js/waypoints.min.js' %}"></script>
			<script src="{% static 'js/jquery.counterup.min.js' %}"></script>			
			<script src="{% static 'js/mail-script.js' %}"></script>	
			<script src="{% static 'js/main.js' %}"></script>	
		</body>
	</html>